### PR TITLE
Added readme

### PR DESCRIPTION
**Pull request by duncanpMS**
You can view the readme at https://github.com/duncanpMS/sonarqube-roslyn-sdk/tree/readme

### CODE REVIEW

**Comment by HSAR** [comment]
"Analyzer must use Roslyn 1.0 or higher."?

**Comment by duncanpMS** [comment]
@HSAR no, it must be Roslyn 1.0 at present. The generator tools are statically built against Roslyn 1.0 so that's the version that is deployed next to the exe. If the analyser package is built against a different version of Roslyn we won't be able to create the analyser objects.

**Comment by HSAR** [comment]
@duncanpMS Ah, I didn't realise that. On a related note you could be specific and say that JDK 7 or higher is required (as that is what SonarQube requires).

**Comment by HSAR** [comment]
LGTM

**Comment by bgavrilMS** [comment]
LGTM

**Comment by duncanpMS** [comment]
@HSAR I'll leave the JDK requirement as it is for now; SonarQube might need v7.0+ to run, but I suspect we don't need that to compile the plugin.

**Pull request merged**
